title: Michaels Site  
author: Michael Gilliam 
email: MichaelGilliam.SE@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
  Hello, this is my new site, where I have completely no idea what im going to write about.
  Please be paitient as I continue to learn what I'm literally going through right now.
theme: minima
# social links
github_username: https://github.com/MichaelGilliam

show_excerpts: true # set to false to remove excerpts on the homepage
